### ISSUE TITLE
Funky formating in interview section

### ISSUE THREAD

**Issue by kerani** [morlockp/escape_the_city#1]
Book version: ebook on Blusky Software Ebooks Reader - (edit: PROBLEM DOES NOT OCCUR ON KINDLE.  Recommend ignoring unless it comes up in another ereader.)

Location: Vol II, interviews, interview with Jared

Problem: Formatting is funky (here and elsewhere with the interviews).  Some questions are placed out of order, or have no answers, and random(?) books are referenced in the middle of text.

Example:

Q: What states or regions did you consider? Why?

Strategic Relocation by Joel Skousen ($50)

and I began to consider other regions like parts of Texas,

**Comment by morlockp** [comment]
>  PROBLEM DOES NOT OCCUR ON KINDLE

excellent update; TY. 

No action item ; closing.
