### ISSUE TITLE
Missed Bolded Question in Interviews

### ISSUE THREAD

**Issue by kerani** [morlockp/escape_the_city#2]
Version: Kindle (fire)

Location: Volume 2 Interviews (Grasshill)

Problem: After the question "If you could time travel" there are 3 paragraphs.  The next question ("What would you do differently in your first few years") is tacked on to the end of the third paragraph.

ALSO - it looks like a copy pasta error in the answer to the "Can you describe your homestead" - looks like two different properties are described.

**Comment by morlockp** [comment]
fixed
