### ISSUE TITLE
ebooks missing Tracy Kidder quote and Kickstarter thanks

### ISSUE THREAD

**Issue by lrprince** [morlockp/escape_the_city#35]
The ebooks (both mobi and epub) are missing the following content present in the PDF versions:
* Tracy Kidder quotation
* Kickstarter backer thanks

**Comment by lrprince** [comment]
Also, the vol 1 mobi has a second, partial ToC at the very end

**Comment by morlockp** [comment]
ToC at the end seems to be part of the ebook format?

I am not adding it / specifically checking that it's not there, and googling for information suggests that this is a thing done by conversion tools.

Backers added.
