### ISSUE TITLE
Column ordering of multi-page Thank Yous (PDF)

### ISSUE THREAD

**Issue by jdclark-unf** [morlockp/escape_the_city#4]
Alphabetical ordering of names for the hardcover and softcover pledges is disjointed across pages, e.g. page viii columns are ordered A-B, F-H, L-N, and R-S, but then page ix columns are ordered B-D, H-K, N-R, and S-W, etc.

**Comment by morlockp** [comment]
not a bug ; columns are contiguous across multiple pages

(left col is A-Brookhart on p vii, Brothers-Cargar on p viii, Donath-Flores on p ix, then continues in 2nd column back on page vii)
