### ISSUE TITLE
Table of Contents, Pagination, and Volume Division (PDF)

### ISSUE THREAD

**Issue by jdclark-unf** [morlockp/escape_the_city#6]
The PDF of volume 1 has a table of contents for both volumes, while volume 2 has no TOC, making it impossible to use hyperlink navigation for volume 2. The EPUBs don't have this problem, but the volume 1 MOBI TOC ends with a broken link to "Error: Reference source not found."

After the front matter, the volume 2 PDF begins on page 637, right where volume 1 left off, in the middle of a list about swimming ponds (the EPUB/MOBI versions at least resume from the beginning of the section on ponds).

**Comment by TJamesCorcoran** [comment]
I suggest using the unified PDF for both volumes; PDFs are a secondary "if it's useful to you and easy for me to generate" format
